Preview extension: switch to LabIcon for the refresh button
voila-dashboards/voila pull request #884
Opened 2021-05-07 17:34 UTC by ohrely

Collaboration with @vickyprakash

2021-05-07 18:56 UTC, ivanov requested changes

2021-05-07 18:56 UTC, ivanov commented on packages/jupyterlab-preview/src/preview.tsx
> +import { refreshIcon } from '@juperlab/ui-components';
looks like a type here.
```suggestion
import { refreshIcon } from '@jupyterlab/ui-components';
```

2021-05-07 19:16 UTC, SylvainCorlay approved these changes

2021-05-28 08:46 UTC, jtpio approved these changes
Thanks!

2021-05-28 08:47 UTC, merged